version: '3.7'

services:
  php-server-app:
    container_name: angular-php
    image: angular-php
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PORT: ${SERVER_PORT}
    ports:
      - 4200:${SERVER_PORT}