version: '3.7'

services:
  php-server-app:
    container_name: angular-js-php
    image: angular-js-php
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - "./server:/app/server"     # mounting